# This is a basic workflow to help you get started with Actions

name: Linter
 
on: push

jobs:
  # Job key
  lint:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      - name: install dependencies
        run: make install


      # Run linter
      - name: Run Linter
        run: make lint

    
